replicaCount: 1

image:
  repository: ghcr.io/reschandreas/secretpaths
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

config:
  vaultAddr: http://127.0.0.1:8200
  kubernetesRole: secretpaths
  kvEngine: secret

serviceAccount:
  create: true
  automount: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: ""
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
          port: 8080
          name: frontend
        - path: /v1
          pathType: Prefix
          port: 8081
          name: backend
  tls: []


service:
  type: ClusterIP
  port: 8080
  serverPort: 8081

podSecurityContext: {}

resources: {}

securityContext: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: http-server
readinessProbe:
  httpGet:
    path: /healthz
    port: http-server