apiVersion: v1
kind: Service
metadata:
  name: {{ include "secretpaths.fullname" . }}
  labels:
    {{- include "secretpaths.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.serverPort }}
      targetPort: http-server
      protocol: TCP
      name: http-server
  selector:
    {{- include "secretpaths.selectorLabels" . | nindent 4 }}
